### ISSUE TITLE
STM32duino_X_NUCLEO_IHM02A1 not woriking on avr

### ISSUE THREAD

**Issue by Athos23** [stm32duino/X-NUCLEO-IHM02A1#11]
hi, I am new to arduino and I have to realize 2 stepper motors controlled by an arduino+X-NUCLEO-IHM02A1
when I try to upload the script (x-nucleo hello world) I get an error message saying that the library is declaring to function on stm32 architecture and could not be compatible with my board (avr architecture)
I am just a newbie, I hope this can be solved easily
Ahtos 23

**Comment by cparata** [comment]
Hi @Athos23 ,
this is due to the fact that the library was tested only with STM32 platforms like Nucleo and Discovery boards. The library is based on Arduino APIs, so it could work also with Arduino boards like Arduino Uno and Arduino Due. Pay attention to connect correctly the pins between the motherboard and the shield (for example SPI SCK pin must be really connected to an SPI clock pin on the target board, etc.). Regarding the Arduino Uno, I think that this board does not have enough memory to run this library. Maybe you can try with a Nucleo-F401RE board that for sure works well with this library.
Best Regards,
Carlo

**Comment by Athos23** [comment]
Understood, thank you!

**Comment by Athos23** [comment]
@cparata , sorry to bother but even when I connect to the right pins following the 'Getting started with X-NUCLEO-IHM02A1' guide i get the same error. [https://www.st.com/resource/en/user_manual/dm00237629-getting-started-with-xnucleoihm02a1-twoaxis-stepper-motor-driver-expansion-board-based-on-l6470-for-stm32-nucleo-stmicroelectronics.pdf](url)
Is it because I have an arduino uno R3 and I don't have enough memory for the library? on the guide is said to be compatible.
Is there an other script that doesn't need all that memory that I can try?

**Comment by cparata** [comment]
Could you share the error that you get during the compilation?

**Comment by Athos23** [comment]
@cparata 
Arduino:1.8.19 (Windows 10), Scheda:"Arduino Uno"

ATTENZIONE: la libreria STM32duino_X_NUCLEO_IHM02A1-1.0.1 dichiara di funzionare sulle architetture stm32 e potrebbe non essere compatibile con la tua scheda che utilizza l'architettura avr

In file included from C:\Users\parco\OneDrive\Documents\Arduino\libraries\STM32duino_X_NUCLEO_IHM02A1-1.0.1\src/XNucleoIHM02A1.h:66:0,

                 from C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:49:

C:\Users\parco\OneDrive\Documents\Arduino\libraries\STM32duino_X_NUCLEO_IHM02A1-1.0.1\src/L6470.h: In member function 'status_t L6470::ReadWrite(uint8_t*, uint8_t*, uint16_t)':

C:\Users\parco\OneDrive\Documents\Arduino\libraries\STM32duino_X_NUCLEO_IHM02A1-1.0.1\src/L6470.h:1418:66: error: no matching function for call to 'SPIClass::transfer(uint8_t*&, uint8_t*&, uint16_t&)'

         dev_spi->transfer(pBufferToWrite, pBufferToRead, NumBytes);

                                                                  ^

In file included from C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:46:0:

C:\Users\parco\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware\arduino\avr\libraries\SPI\src/SPI.h:208:25: note: candidate: static uint8_t SPIClass::transfer(uint8_t)

   inline static uint8_t transfer(uint8_t data) {

                         ^~~~~~~~

C:\Users\parco\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware\arduino\avr\libraries\SPI\src/SPI.h:208:25: note:   candidate expects 1 argument, 3 provided

C:\Users\parco\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware\arduino\avr\libraries\SPI\src/SPI.h:244:22: note: candidate: static void SPIClass::transfer(void*, size_t)

   inline static void transfer(void *buf, size_t count) {

                      ^~~~~~~~

C:\Users\parco\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware\arduino\avr\libraries\SPI\src/SPI.h:244:22: note:   candidate expects 2 arguments, 3 provided

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino: In function 'void setup()':

X_NUCLEO_IHM02A1_HelloWorld:142:28: error: 'D11' was not declared in this scope

     dev_spi = new SPIClass(D11, D12, D13);

                            ^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:142:28: note: suggested alternative: 'B11'

     dev_spi = new SPIClass(D11, D12, D13);

                            ^~~

                            B11

X_NUCLEO_IHM02A1_HelloWorld:142:33: error: 'D12' was not declared in this scope

     dev_spi = new SPIClass(D11, D12, D13);

                                 ^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:142:33: note: suggested alternative: 'DD2'

     dev_spi = new SPIClass(D11, D12, D13);

                                 ^~~

                                 DD2

X_NUCLEO_IHM02A1_HelloWorld:142:38: error: 'D13' was not declared in this scope

     dev_spi = new SPIClass(D11, D12, D13);

                                      ^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:142:38: note: suggested alternative: 'DD3'

     dev_spi = new SPIClass(D11, D12, D13);

                                      ^~~

                                      DD3

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:142:41: warning: new initializer expression list treated as compound expression [-fpermissive]

     dev_spi = new SPIClass(D11, D12, D13);

                                         ^

X_NUCLEO_IHM02A1_HelloWorld:146:83: error: 'D4' was not declared in this scope

     x_nucleo_ihm02a1 = new XNucleoIHM02A1(&L6470_init[0], &L6470_init[1], A4, A5, D4, A2, dev_spi);

                                                                                   ^~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:146:83: note: suggested alternative: 'A4'

     x_nucleo_ihm02a1 = new XNucleoIHM02A1(&L6470_init[0], &L6470_init[1], A4, A5, D4, A2, dev_spi);

                                                                                   ^~

                                                                                   A4

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino: In function 'void loop()':

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:58:22: warning: integer overflow in expression [-Woverflow]

 #define STEPS_1 (400 * 128)   /* 1 revolution given a 400 steps motor configured at 1/128 microstep mode. */

                  ~~~~^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:193:22: note: in expansion of macro 'STEPS_1'

     SerialPort.print(STEPS_1);

                      ^~~~~~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:58:22: warning: integer overflow in expression [-Woverflow]

 #define STEPS_1 (400 * 128)   /* 1 revolution given a 400 steps motor configured at 1/128 microstep mode. */

                  ~~~~^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:197:40: note: in expansion of macro 'STEPS_1'

     motors[0]->move(StepperMotor::FWD, STEPS_1);

                                        ^~~~~~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:58:22: warning: integer overflow in expression [-Woverflow]

 #define STEPS_1 (400 * 128)   /* 1 revolution given a 400 steps motor configured at 1/128 microstep mode. */

                  ~~~~^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:59:18: note: in expansion of macro 'STEPS_1'

 #define STEPS_2 (STEPS_1 * 2)

                  ^~~~~~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:221:22: note: in expansion of macro 'STEPS_2'

     SerialPort.print(STEPS_2);

                      ^~~~~~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:58:22: warning: integer overflow in expression [-Woverflow]

 #define STEPS_1 (400 * 128)   /* 1 revolution given a 400 steps motor configured at 1/128 microstep mode. */

                  ~~~~^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:59:18: note: in expansion of macro 'STEPS_1'

 #define STEPS_2 (STEPS_1 * 2)

                  ^~~~~~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:225:40: note: in expansion of macro 'STEPS_2'

     motors[0]->move(StepperMotor::BWD, STEPS_2);

Più di una libreria trovata per "XNucleoIHM02A1.h"

                                        ^~~~~~~

Usata: C:\Users\parco\OneDrive\Documents\Arduino\libraries\STM32duino_X_NUCLEO_IHM02A1-1.0.1

Non usata: C:\Users\parco\OneDrive\Documents\Arduino\libraries\STM32duino_X_NUCLEO_IHM02A1-1.0.2

Non usata: C:\Users\parco\OneDrive\Documents\Arduino\libraries\X-NUCLEO-IHM02A1-main

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:58:22: warning: integer overflow in expression [-Woverflow]

 #define STEPS_1 (400 * 128)   /* 1 revolution given a 400 steps motor configured at 1/128 microstep mode. */

                  ~~~~^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:324:22: note: in expansion of macro 'STEPS_1'

     SerialPort.print(STEPS_1);

                      ^~~~~~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:58:22: warning: integer overflow in expression [-Woverflow]

 #define STEPS_1 (400 * 128)   /* 1 revolution given a 400 steps motor configured at 1/128 microstep mode. */

                  ~~~~^~~

C:\Users\parco\Downloads\STM32duino_X_NUCLEO_IHM02A1-1.0.2\STM32duino_X_NUCLEO_IHM02A1-1.0.2\examples\X_NUCLEO_IHM02A1_HelloWorld\X_NUCLEO_IHM02A1_HelloWorld.ino:328:40: note: in expansion of macro 'STEPS_1'

     motors[0]->move(StepperMotor::FWD, STEPS_1);

                                        ^~~~~~~

exit status 1

'D11' was not declared in this scope

**Comment by cparata** [comment]
Ok, I understood. In the sample sketch, try to remove "D" from any "Dxy" pin name. So, for example "D11" becomes simply "11" and so on.

**Comment by cparata** [comment]
Maybe, there are also some other small changes to do. So, I'm sorry but it seems that the library is not strictly compliant with Arduino Uno. Any contribution to do it compliant is welcome.

**Comment by Athos23** [comment]
I will try, ahahahah
thank you very much for the help so far
