### ISSUE TITLE
IHM02A1 and Raspberry 4B

### ISSUE THREAD

**Issue by adrianlupoian** [stm32duino/X-NUCLEO-IHM02A1#12]
Hi, can anybody provide me an example how to connect Raspberry 4 and Nucleo IHM02A1 board (2 motors) ? Also , there is an python library to manage the motors? Thank you.

**Comment by cparata** [comment]
Hello @adrianlupoian ,
this library is for Arduino based boards. Raspberry 4B is a Linux based board, so you cannot use this library on that platform.
Best Regards,
Carlo

**Comment by adrianlupoian** [comment]
Thank you for your response.
I know that. For me is important to know how this board works. If you know
some place where I can find more info please let me know.

**Comment by fpistm** [comment]
> Thank you for your response. I know that. For me is important to know how this board works. If you know some place where I can find more info please let me know.

https://www.st.com/en/ecosystems/x-nucleo-ihm02a1.html

**Comment by adrianlupoian** [comment]
Thank you.
