### ISSUE TITLE
NODE_F207ZG not found, and having motors move

### ISSUE THREAD

**Issue by adamaero** [stm32duino/X-NUCLEO-IHM02A1#8]
I supplied the expansion board for the stepper motor drivers with 24 V. 
I tried running the example program on a Nucleo-144 F767ZU and an Arduino Mega2560. 

Here is the same error message for both attempts:
```
Arduino: 1.8.9 (Windows 7), Board: "Nucleo-144, Nucleo F207ZG, Mass Storage, Enabled (generic 'Serial'), None, Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

A subdirectory or file sketch already exists.

Sketch uses 34916 bytes (3%) of program storage space. Maximum is 1048576 bytes.
Global variables use 1348 bytes (1%) of dynamic memory, leaving 129724 bytes for local variables. Maximum is 131072 bytes.
NODE_F207ZG not found. Please ensure the device is correctly connected.
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by fpistm** [comment]
Hi @adamaero 
you have to select the right "**Board part number**" in the Tools Menu.

https://github.com/stm32duino/wiki/wiki/Getting-Started

**Comment by adamaero** [comment]
Thank you. It seems to upload to the F767ZI board. 
I'm used to Arduino programs automatically running. The stepper motors are not moving. 
Is there an additional step I'm missing?

![Nucleo-144](https://user-images.githubusercontent.com/26505046/61724033-be0cf100-ad32-11e9-843e-60d6ffbb8238.png)

**Comment by fpistm** [comment]
@cparata any though on this?

**Comment by cparata** [comment]
Hi,
I guess the issue is due to the fact that on F767ZI in D3 (PE13) we do not have the SPI1 clock. So you are obliged to use D13 instead D3 as SPI clock. In order to do that you need to unsolder SB34 and solder SB12 on X-NUCLEO-IHM02A1 and then initialize the SPI instance in the sketch in this way:

dev_spi = new SPIClass(D11, D12, D13);

I hope that this tip can help you to solve your issue.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Thanks  @cparata , that's this kind of issue I though. 
@adamaero  You could try to wire manually before rework the SB in order to test.

**Comment by adamaero** [comment]
Success. Thank you both very much! 
Now I just need to figure out how to add a third motor to the program (using a second X-NUCLEO-IHM02A1), and integrate that program with the encoders.
